### PR TITLE
Introduce reduced

### PR DESCRIPTION
**Pull request by sventschui**

### CODE REVIEW

**Comment by donnut** [comment]
I'm not sure what you are trying to achief with the extra interface. Could you explain this please?

**Comment by sventschui** [comment]
The return value of R.reduced is not the value passed. It's sth that is not guaranteed to be stable. So using that interface will make sure the return value is not mistaken as the same value as passed to reduced

**Comment by donnut** [comment]
Ahh, I completely missed reduceD. Now it makes sense to me. Maybe you could change the def to
```typescript
reduced<T>(elem: any): Reduced<T>;
```

**Comment by sventschui** [comment]
That would not make any sense. The thing on the `elem: T` is that `R.reduce` will return what you passed into `R.reduced` as `elem` and will therefor be of the same type as `elem` was. So `elem` needs to be of type `T`

**Comment by donnut** [comment]
> So elem needs to be of type T

But your code now says `elem` is (implivitely) of type `any` as the type is omitted. I agree it should be `elem: T`

Do you have a test case we can included in the test file?

Thanks!

**Comment by sventschui** [comment]
> But your code now says elem is (implivitely) of type any as the type is omitted. I agree it should be elem: T

Fixed that with c1ca518

I'll have a look into tests tomorrow

**Comment by donnut** [comment]
:+1:

**Comment by donnut** [comment]
@sventschui Do you have time to look into the tests? If not, no problem, then I'll try to add some.

**Comment by sventschui** [comment]
I currently don't have any spare time to write these tests. Sorry :/

**Comment by donnut** [comment]
@sventschui No problem, thanks for letting me know. I'll merge your pr and add some tests later on.

**Pull request merged**
