### PR TITLE
more overloads for R.split

### PR DESCRIPTION
**Pull request by nshahpazov**
Added different overloads for R.split. R.split works as well as with string also with regular expressions too. It may be curried so it can return a function.

### CODE REVIEW

**Comment by donnut** [comment]
Good catch. Thanks.
Maybe the documentation of Ramda should mention the possiblity of a regular expression as the first argument too, @davidchambers?

**Comment by donnut** [comment]
@nshahpazov do you want to extend the tests of split to cover currying and regexp too?

**Comment by nshahpazov** [comment]
@donnut sore, why not.

**Comment by donnut** [comment]
I've merged the changes for now. Hope we can add some more tests later.

**Pull request merged**
