### PR TITLE
Unnest and flatten

### PR DESCRIPTION
**Pull request by jcristovao**
Ok, I am a bit more unsure about this one, but I still think it is correct:

A regular use of both unnest and flatten is to drop a dimension of an array, and hence the type signature should allow it. 

What do you think?
João

### CODE REVIEW

**Comment by donnut** [comment]
I'm not sure adding a list of a list type is adding any type safety for unnest and flatten. Do you have an example that shows this?

Currying evolve looks fine.

**Comment by jcristovao** [comment]
If we slightly modify the test to a more informative (here used exclusively to compare the two types):

    R.equals(R.unnest([[1, 2], [3, 4], [5, 6]]),[1,2,3,4,5,6]); //=> true 

We can verify that it does not compile without the extra definition that I gave.

    ramda-tests.ts(813,5): error TS2453: The type argument for type parameter 'T' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
      Type argument candidate 'number[][]' is not a valid type argument because it is not a supertype of candidate 'number[]'.
    Type 'number' is not assignable to type 'number[]'.

My use case is of course different, but it does boil down to this same error message.

**Comment by donnut** [comment]
You convinced me ;)
Thanks

**Comment by jcristovao** [comment]
Cool :)

**Pull request merged**
