### PR TITLE
Improve typing of toPairs and toPairsIn

### PR DESCRIPTION
**Pull request by forbesmyester**
I __believe__ this is better typing for `toPairs()` and `toPairsIn()` though this is my first ever typescript definition file. (so be gentle if it's no good!)

### CODE REVIEW

**Comment by forbesmyester** [comment]
Hmmm, well guess not. Will have another go!

**Comment by forbesmyester** [comment]
Tests fixed up, let me know what you think :-)

**Comment by donnut** [comment]
Look fine. Thanks

**Comment by forbesmyester** [comment]
Awesome,  thanks ☺️

**Pull request merged**
